name: dairy_traceability
version: "1.0.0"
config-version: 2
profile: dairy_traceability

model-paths: ["models"]
seed-paths: ["seeds"]

models:
  dairy_traceability:
    +materialized: view
    +schema: analytics
